# Generated by Django 4.1.2 on 2022-10-31 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timespend',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeproject.attendance'),
        ),
    ]
