# Generated by Django 4.1.2 on 2022-10-31 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeproject', '0002_alter_timespend_emp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timespend',
            old_name='emp',
            new_name='attendace',
        ),
    ]
