# Generated by Django 4.1.2 on 2022-11-01 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeproject', '0003_rename_emp_timespend_attendace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timespend',
            old_name='attendace',
            new_name='attendance',
        ),
    ]
