# Generated by Django 4.1.2 on 2022-11-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeproject', '0004_rename_attendace_timespend_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default="2022-11-01"),
            preserve_default=False,
        ),
    ]
