# Generated by Django 4.1.2 on 2022-11-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeproject', '0010_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timespend',
            name='punchin',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
