# Generated by Django 4.1.2 on 2022-11-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeproject', '0011_alter_timespend_punchin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timespend',
            name='punchin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
