# Generated by Django 4.1.2 on 2022-11-01 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeproject', '0013_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
    ]
